# Generated by Django 3.0.3 on 2020-02-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='costo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
