# Generated by Django 3.0.3 on 2020-03-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200301_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='name',
        ),
    ]
