# Generated by Django 3.0.3 on 2020-03-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200301_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
