# Generated by Django 3.0.3 on 2020-03-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_factura_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Delivery'),
        ),
    ]
