# Generated by Django 3.0.3 on 2020-03-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200301_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='divisa',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='facturadetail',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
