# Generated by Django 3.0.3 on 2020-03-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200301_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='clientes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado'),
        ),
    ]
