# Generated by Django 3.0.3 on 2020-03-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200302_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
