# Generated by Django 3.0.3 on 2020-03-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200302_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Factura'),
        ),
    ]
