# Generated by Django 3.0.3 on 2020-03-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200304_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Instrumento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='divisa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Divisa'),
        ),
    ]
