# Generated by Django 3.0.3 on 2020-03-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200304_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empleado',
        ),
    ]
