# Generated by Django 3.0.3 on 2020-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200305_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fecha_vencimiento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
